// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ACxZAp0yR3VvVEY8M9_Jw5mNjr_h64I',
    appId: '1:253215509115:web:667db20956f6353554b0de',
    messagingSenderId: '253215509115',
    projectId: 'atividade-extracurricular',
    authDomain: 'atividade-extracurricular.firebaseapp.com',
    storageBucket: 'atividade-extracurricular.appspot.com',
    measurementId: 'G-LZ40W2HYTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9OrolFsjjNTYsfXZgK6ySndbvVG8JX4M',
    appId: '1:253215509115:android:53aface4a6fd44cc54b0de',
    messagingSenderId: '253215509115',
    projectId: 'atividade-extracurricular',
    storageBucket: 'atividade-extracurricular.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC29mEoOg9an_6l_djfm-gVWBUKkpqEEDA',
    appId: '1:253215509115:ios:09062986d4f5118554b0de',
    messagingSenderId: '253215509115',
    projectId: 'atividade-extracurricular',
    storageBucket: 'atividade-extracurricular.appspot.com',
    iosBundleId: 'com.example.controleAtividadeExtracurricular',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC29mEoOg9an_6l_djfm-gVWBUKkpqEEDA',
    appId: '1:253215509115:ios:73ecbdc6301effa554b0de',
    messagingSenderId: '253215509115',
    projectId: 'atividade-extracurricular',
    storageBucket: 'atividade-extracurricular.appspot.com',
    iosBundleId: 'com.example.controleAtividadeExtracurricular.RunnerTests',
  );
}
